removed pagure content and parameteres from templates
thoth-station/tensorflow-build-s2i pull request #11
Opened 2018-08-08 20:41 UTC by harshad16

2018-08-08 20:44 UTC, sub-mod requested changes
change GIT_TOKEN var in run script
check if GIT_TOKEN var is used anywhere else in the repo

2018-08-08 20:46 UTC, harshad16 commented
@subin we can use the GIT_TOKEN variable by providing it with SESHETA_GITHUB_ACCESS_TOKEN right?

2018-08-13 17:00 UTC, sub-mod commented on tensorflow-build-job.json
> +                                        "value": "${SESHETA_GITHUB_ACCESS_TOKEN}"
ok good.

2018-08-13 17:00 UTC, sub-mod approved these changes

2018-08-13 17:00 UTC, merged